{% set version = "1.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-msgps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/msgps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/msgps/msgps_{{ version }}.tar.gz
  sha256: 2eda002d55ae47a544de2ed63e2853e1a17c7fae865e954deb796edbc27573bd

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('msgps')"           # [not win]
    - "\"%R%\" -e \"library('msgps')\""  # [win]

about:
  home: http://www.keihirose.com/.
  license: GPL-2.0-or-later
  summary: This package computes the degrees of freedom of the lasso, elastic net, generalized elastic net and adaptive lasso based on the generalized path seeking algorithm.  The optimal model can be selected by model selection criteria including Mallows' Cp, bias-corrected AIC (AICc), generalized cross validation (GCV)
    and BIC.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: msgps
# Type: Package
# Title: Degrees of freedom of elastic net, adaptive lasso and generalized elastic net
# Version: 1.3
# Date: 2012-5-17
# Author: Kei Hirose
# Maintainer: Kei Hirose <mail@keihirose.com>
# Description: This package computes the degrees of freedom of the lasso, elastic net, generalized elastic net and adaptive lasso based on the generalized path seeking algorithm.  The optimal model can be selected by model selection criteria including Mallows' Cp, bias-corrected AIC (AICc), generalized cross validation (GCV) and BIC.
# License: GPL (>= 2)
# URL: http://www.keihirose.com/.
# Packaged: 2012-05-17 01:22:59 UTC; hirosekei
# Repository: CRAN
# Date/Publication: 2012-05-17 06:51:28
# NeedsCompilation: yes
